# Google Cloud Build Configuration
# Builds and deploys the Lightspeed Agent to Cloud Run
#
# Usage:
#   gcloud builds submit --config=cloudbuild.yaml \
#     --substitutions=_SERVICE_NAME=lightspeed-agent,_REGION=us-central1
#
# Required substitutions:
#   _SERVICE_NAME: Cloud Run service name
#   _REGION: Deployment region
#
# Optional substitutions:
#   _IMAGE_TAG: Container image tag (default: latest)

substitutions:
  _SERVICE_NAME: lightspeed-agent
  _REGION: us-central1
  _IMAGE_TAG: latest

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  # ==========================================================================
  # Step 1: Build the container image
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_IMAGE_TAG}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '-f'
      - 'Containerfile'
      - '.'

  # ==========================================================================
  # Step 2: Push the container image to Container Registry
  # ==========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}'
    waitFor:
      - 'build'

  # ==========================================================================
  # Step 3: Deploy to Cloud Run
  # ==========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_IMAGE_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--port'
      - '8000'
      - '--cpu'
      - '2'
      - '--memory'
      - '2Gi'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'GOOGLE_GENAI_USE_VERTEXAI=TRUE,GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_LOCATION=${_REGION},AGENT_HOST=0.0.0.0,AGENT_PORT=8000,LOG_FORMAT=json'
      - '--set-secrets'
      - 'GOOGLE_API_KEY=google-api-key:latest,LIGHTSPEED_CLIENT_ID=lightspeed-client-id:latest,LIGHTSPEED_CLIENT_SECRET=lightspeed-client-secret:latest,RED_HAT_SSO_CLIENT_ID=redhat-sso-client-id:latest,RED_HAT_SSO_CLIENT_SECRET=redhat-sso-client-secret:latest,DATABASE_URL=database-url:latest,REDIS_URL=redis-url:latest'
      - '--service-account'
      - 'lightspeed-agent@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
    waitFor:
      - 'push'

images:
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_IMAGE_TAG}'
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'

tags:
  - 'lightspeed-agent'
  - 'cloud-run'
